version: '3.2'
services:
  relay:
    container_name: webhookrelay
    image: webhookrelay/webhookrelayd:latest
    restart: always
    # environment:
      # Authentication
      # - RELAY_KEY=<HERE IS YOUR RELAY KEY>
      # - RELAY_SECRET=<HERE IS YOUR RELAY SECRET>
      # buckets list to subscribe
      # - BUCKETS=<HERE IS YOUR RELAY BUCKET>

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    restart: always
    privileged: true
    user: root
    ports:
      - 9999:8080
      - 50000:50000
    volumes:
      - /var/lib/docker/volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    
